#include "src/include.h"
#include "src/isajet.h"
#include "src/softsusy.h"
#include "src/suspect.h"
#include "src/spheno.h"
#include "src/higgsbounds.h"


#define USE_ISAJET /* to be commented if ISAJET (>=7.80) is unavailable */

#define USE_HIGGSBOUNDS /* to be commented if HIGGSBOUNDS is unavailable */

/*--------------------------------------------------------------------*/
/* Calculation of the observables, corresponding to a Hypercharged AMSB point generated by ISAJET */
/*--------------------------------------------------------------------*/

int main(int argc,char** argv)
{
	char name[50];
	double alpha,m32,tanb,A0,sgnmu,mtop,mbot,alphas_mz,delta0;

	if(argc<4) 
	{ 
		printf(" This program needs 3 parameters:\n"
		"   alpha    \n"
		"   m3/2    gravitino mass\n"
		"   tanb      tan(beta) \n");
		printf(" Auxiliary parameters are:\n"
		"   sgnmu    +/-1,  sign of Higgsino mass term (default 1)\n"    
		"   mtop     top quark pole mass\n");
		exit(1); 
  	} 
	else  
  	{
		sscanf(argv[1],"%lf",&alpha);
     		sscanf(argv[2],"%lf",&m32);
     		sscanf(argv[3],"%lf",&tanb);
     		if(argc>4) sscanf(argv[4],"%lf",&sgnmu); else sgnmu=1;
     		if(argc>5) sscanf(argv[5],"%lf",&mtop); else mtop=173.3;   
  	}	


	int filesOK=1;
#ifdef USE_ISAJET
	if(!test_file(ISAJET)) 
	{
		printf("\"%s\" absent. Please check the ISAJET path or comment \"#define USE_ISAJET\" in hcamsb.c\n",ISAJET);
		filesOK=0;
	}
#endif
#ifdef USE_HIGGSBOUNDS
	if(!test_file(HBwithFH)) 
	{
		printf("\"%s\" absent. Please check the HBwithFH path or comment \"#define USE_HIGGSBOUNDS\" in hcamsb.c\n",HBwithFH);
		filesOK=0;
	}
#endif
	if(!filesOK) return 1;


	if(!test_file("tmp")) system("mkdir tmp");
	chdir("tmp");

#ifdef USE_ISAJET
	sprintf(name,"hcamsb_isajet%d.tmplha",getpid());
	isajet_hcamsb(alpha, m32, tanb, sgnmu, mtop, name);
	printf("SLHA file generated by ISAJET\n");
	
	delta0=delta0_calculator(name);
	if(delta0 !=0.)
	{
		printf("delta0=%.3e\n",delta0);
       		printf("BR_bsgamma=%.3e\n",bsgamma_calculator(name));
		printf("BR_Bsmumu=%.3e\n",Bsmumu_calculator(name));
      		printf("BR_Btaunu=%.3e\n",Btaunu_calculator(name));
      		printf("Rtaunu=%.3e\n",RBtaunu_calculator(name));
      		printf("BR_BDtaunu=%.3e\n",BDtaunu_calculator(name));
      		printf("BR_BDtaunu/BR_BDenu=%.3e\n",BDtaunu_BDenu_calculator(name));
     		printf("BR_Dstaunu=%.3e\n",Dstaunu_calculator(name));
     		printf("BR_Dsmunu=%.3e\n",Dsmunu_calculator(name));
     		printf("BR_Dmunu=%.3e\n",Dmunu_calculator(name));
      		printf("BR_Kmunu/BR_pimunu=%.3e\n",Kmunu_pimunu_calculator(name));
     		printf("Rl23=%.3e\n",Rl23_calculator(name));
		printf("a_muon=%.3e\n",muon_gm2_calculator(name));
       		printf("charged_LSP=%d\n",charged_LSP_calculator(name));
#ifdef USE_HIGGSBOUNDS
		printf("excluded_HiggsBounds=%d\n",(higgsbounds_calculator(name)>1.));
#else
 		printf("excluded_Higgs_mass=%d\n",excluded_Higgs_mass_calculator(name));
#endif
 		printf("excluded_SUSY_mass=%d\n",excluded_SUSY_mass_calculator(name));
		flha_generator(name,"../output.flha");
		printf("output.flha generated\n\n");	
	}
	else printf("Invalid point\n\n");
	sprintf(name,"rm hcamsb_isajet%d.tmplha",getpid());
	system(name); 
#endif

	return 1;
}
