#include "src/include.h"

#define USE_SOFTSUSY

/*--------------------------------------------------------------------*/
/* Calculation of the observables, corresponding to a NUHM point generated by SOFTSUSY */
/*--------------------------------------------------------------------*/

int main(int argc,char** argv)
{
	char name[50];
	float m0,m12,tanb,A0,mu,mA,mtop,mbot,alphas_mz,delta0;

	if(argc<7) 
	{ 
		printf(" This program needs 6 parameters:\n"
		"   m0      common scalar mass at GUT scale\n"
           	"   m12     common gaugino mass at GUT scale\n"
		"   A0      trilinear soft breaking parameter at GUT scale\n"
		"   tanb    tan(beta) \n"
		"   mu      mu parameter\n"
		"   mA      CP-odd Higgs mass\n");
		printf(" Auxiliary parameters are:\n"
		"   mtop    top quark pole mass\n"
		"   mbot    Mb(Mb) scale independent b-quark mass (SOFTSUSY only)\n"
		"   alphas_mz  strong coupling at MZ (SOFTSUSY only)\n");                        
		exit(1); 
	} 
	else  
	{
		sscanf(argv[1],"%f",&m0);
		sscanf(argv[2],"%f",&m12);
		sscanf(argv[3],"%f",&A0);
		sscanf(argv[4],"%f",&tanb);
		sscanf(argv[5],"%f",&mu);
		sscanf(argv[6],"%f",&mA);
		if(argc>7) sscanf(argv[7],"%f",&mtop); else mtop=172.4;   
		if(argc>8) sscanf(argv[8],"%f",&mbot); else mbot=4.2;
		if(argc>9) sscanf(argv[9],"%f",&alphas_mz); else alphas_mz=0.1176;
	}	
	sprintf(name,"nuhm.lha");

#ifdef USE_SOFTSUSY
	softsusy_nuhm(m0, m12, tanb, A0, mu, mA, mtop, mbot, alphas_mz, name);
	delta0=delta0_calculator(name);
	if(delta0 !=0.)
	{
		printf("delta0=%.3e\n",delta0);
       		printf("BR_bsgamma=%.3e\n",bsgamma_calculator(name));
      		printf("BR_Btaunu=%.3e\n",Btaunu_calculator(name));
      		printf("Rtaunu=%.3e\n",RBtaunu_calculator(name));
      		printf("BR_Kmunu/BR_pimunu=%.3e\n",Kmunu_pimunu_calculator(name));
     		printf("Rl23=%.3e\n",Rl23_calculator(name));
      		printf("BR_BDtaunu=%.3e\n",BDtaunu_calculator(name));
      		printf("BR_BDtaunu/BR_BDenu=%.3e\n",BDtaunu_BDenu_calculator(name));
		printf("BR_Bsmumu=%.3e\n",Bsmumu_calculator(name));
     		printf("BR_Dstaunu=%.3e\n",Dstaunu_calculator(name));
     		printf("BR_Dsmunu=%.3e\n",Dsmunu_calculator(name));
		printf("a_muon=%.3e\n",muon_gm2_calculator(name));
		printf("excluded_mass=%d\n\n",excluded_mass_calculator(name));
	}
	else printf("Invalid point\n\n");
#endif

	sprintf(name,"rm nuhm.lha");
	system(name);		
	return 1;
}
