#include "src/include.h"
#include "src/isajet.h"
#include "src/softsusy.h"
#include "src/higgsbounds.h"
#include "src/hdecay.h"


#define USE_ISAJET /* to be commented if ISAJET (>=7.80) is unavailable */
#define USE_SOFTSUSY /* to be commented if SOFTSUSY is unavailable */

#define USE_HIGGSBOUNDS /* to be commented if HIGGSBOUNDS or HDECAY is unavailable */

/*--------------------------------------------------------------------*/
/* Calculation of the observables, corresponding to a NUHM point generated by SOFTSUSY and/or ISAJET */
/*--------------------------------------------------------------------*/

int main(int argc,char** argv)
{
	char name[50];
	double m0,m12,tanb,A0,mu,mA,mtop,mbot,alphas_mz,delta0,omega;

	if(argc<7) 
	{ 
		printf(" This program needs 6 parameters:\n"
		"   m0      common scalar mass at GUT scale\n"
           	"   m12     common gaugino mass at GUT scale\n"
		"   A0      trilinear soft breaking parameter at GUT scale\n"
		"   tanb    tan(beta) \n"
		"   mu      mu parameter\n"
		"   mA      CP-odd Higgs mass\n");
		printf(" Auxiliary parameters are:\n"
		"   mtop    top quark pole mass\n"
		"   mbot    Mb(Mb) scale independent b-quark mass (SOFTSUSY only)\n"
		"   alphas_mz  strong coupling at MZ (SOFTSUSY only)\n");                        
		exit(1); 
	} 
	else  
	{
		sscanf(argv[1],"%lf",&m0);
		sscanf(argv[2],"%lf",&m12);
		sscanf(argv[3],"%lf",&A0);
		sscanf(argv[4],"%lf",&tanb);
		sscanf(argv[5],"%lf",&mu);
		sscanf(argv[6],"%lf",&mA);
		if(argc>7) sscanf(argv[7],"%lf",&mtop); else mtop=173.3;   
		if(argc>8) sscanf(argv[8],"%lf",&mbot); else mbot=4.19;
		if(argc>9) sscanf(argv[9],"%lf",&alphas_mz); else alphas_mz=0.1176;
	}	

	int filesOK=1;
#ifdef USE_ISAJET
	if(!test_file(ISAJET)) 
	{
		printf("\"%s\" absent. Please check the ISAJET path or comment \"#define USE_ISAJET\" in nuhm.c\n",ISAJET);
		filesOK=0;
	};
#endif
#ifdef USE_SOFTSUSY
	if(!test_file(SOFTSUSY)) 
	{
		printf("\"%s\" absent. Please check the SOFTSUSY path or comment \"#define USE_SOFTSUSY\" in nuhm.c\n",SOFTSUSY);
		filesOK=0;
	};
#endif
#ifdef USE_HIGGSBOUNDS
	if(!test_file(HIGGSBOUNDS)) 
	{
		printf("\"%s\" absent. Please check the HIGGSBOUNDS path or comment \"#define USE_HIGGSBOUNDS\" in nuhm.c\n",HIGGSBOUNDS);
		filesOK=0;
	};
	if(!test_file(HDECAY)) 
	{
		printf("\"%s\" absent. Please check the HDECAY path or comment \"#define USE_HIGGSBOUNDS\" in nuhm.c\n",HDECAY);
		filesOK=0;
	};
#endif
	if(!filesOK) return 1;


	if(!test_file("tmp")) system("mkdir tmp");
	chdir("tmp");

#ifdef USE_SOFTSUSY
	sprintf(name,"nuhm_softsusy%d.tmplha",getpid());
	softsusy_nuhm(m0, m12, tanb, A0, mu, mA, mtop, mbot, alphas_mz, name);
	delta0=delta0_calculator(name);
	if(delta0 !=0.)
	{
		printf("SLHA file generated by SOFTSUSY\n");
		printf("delta0=%.3e\n",delta0);
       		printf("BR_bsgamma=%.3e\n",bsgamma_calculator(name));
      		printf("BR_Btaunu=%.3e\n",Btaunu_calculator(name));
      		printf("Rtaunu=%.3e\n",RBtaunu_calculator(name));
      		printf("BR_Kmunu/BR_pimunu=%.3e\n",Kmunu_pimunu_calculator(name));
     		printf("Rl23=%.3e\n",Rl23_calculator(name));
      		printf("BR_BDtaunu=%.3e\n",BDtaunu_calculator(name));
      		printf("BR_BDtaunu/BR_BDenu=%.3e\n",BDtaunu_BDenu_calculator(name));
		printf("BR_Bsmumu=%.3e\n",Bsmumu_calculator(name));
     		printf("BR_Dmunu=%.3e\n",Dmunu_calculator(name));
     		printf("BR_Dstaunu=%.3e\n",Dstaunu_calculator(name));
     		printf("BR_Dsmunu=%.3e\n",Dsmunu_calculator(name));
		printf("a_muon=%.3e\n",muon_gm2_calculator(name));
       		printf("charged_LSP=%d\n",charged_LSP_calculator(name));
#ifdef USE_HIGGSBOUNDS
		printf("excluded_HiggsBounds=%d\n",higgsbounds_calculator(name));
#else
 		printf("excluded_Higgs_mass=%d\n",excluded_Higgs_mass_calculator(name));
#endif
 		printf("excluded_SUSY_mass=%d\n",excluded_SUSY_mass_calculator(name));
		flha_generator(name,"../output1.flha");
		printf("output1.flha generated\n\n");	
	}
	else printf("Invalid point\n\n");
	sprintf(name,"rm nuhm_softsusy%d.tmplha",getpid());
	system(name);		
#endif

#ifdef USE_ISAJET
	sprintf(name,"nuhm_isajet%d.tmplha",getpid());
	isajet_nuhm(m0, m12, tanb, A0, mu, mA, mtop, name);
	delta0=delta0_calculator(name);
	if(delta0 !=0.)
	{
#if LOOPCOMP!=0
		omega=relic_calculator(name);
#endif
		printf("SLHA file generated by ISAJET\n");
		printf("delta0=%.3e\n",delta0);
       		printf("BR_bsgamma=%.3e\n",bsgamma_calculator(name));
      		printf("BR_Btaunu=%.3e\n",Btaunu_calculator(name));
      		printf("Rtaunu=%.3e\n",RBtaunu_calculator(name));
      		printf("BR_Kmunu/BR_pimunu=%.3e\n",Kmunu_pimunu_calculator(name));
     		printf("Rl23=%.3e\n",Rl23_calculator(name));
      		printf("BR_BDtaunu=%.3e\n",BDtaunu_calculator(name));
      		printf("BR_BDtaunu/BR_BDenu=%.3e\n",BDtaunu_BDenu_calculator(name));
		printf("BR_Bsmumu=%.3e\n",Bsmumu_calculator(name));
     		printf("BR_Dmunu=%.3e\n",Dmunu_calculator(name));
     		printf("BR_Dstaunu=%.3e\n",Dstaunu_calculator(name));
     		printf("BR_Dsmunu=%.3e\n",Dsmunu_calculator(name));
		printf("a_muon=%.3e\n",muon_gm2_calculator(name));
       		printf("charged_LSP=%d\n",charged_LSP_calculator(name));
#ifdef USE_HIGGSBOUNDS
		printf("excluded_HiggsBounds=%d\n",higgsbounds_calculator(name));
#else
 		printf("excluded_Higgs_mass=%d\n",excluded_Higgs_mass_calculator(name));
#endif
 		printf("excluded_SUSY_mass=%d\n",excluded_SUSY_mass_calculator(name));
		flha_generator(name,"../output2.flha");
		printf("output2.flha generated\n\n");	
	}
	else printf("Invalid point\n\n");
	sprintf(name,"rm nuhm_isajet%d.tmplha",getpid());
	system(name);	
#endif

	return 1;
}
